### ISSUE TITLE
Allow to transparently pass options to cherry-pick

### ISSUE THREAD

**Issue by earl-warren** [kiegroup/git-backporting#111]
When backporting in Forgejo the `-x` option is used to keep track of the relationship with the original commit. Without this option, someone would need to figure out the pull request it comes from to know from where it was backported which is not self contained. 

A `cherry-pick-options` could be a list of options transparently passed to cherry-pick and empty by default.

An alternative would be to have a  dedicated`cherry-pick-x` options but that would only cover this one option. Anyone willing to use another option for whatever reason would need to add another flag which is less flexible and maintainable.

**Comment by lampajr** [comment]
I like the idea of `cherry-pick-options` such that we don't have to deal with many other options (if needed in the future)

**Comment by earl-warren** [comment]
I'll work on that this week-end then.

**Comment by earl-warren** [comment]
Manually tested at https://code.forgejo.org/earl-warren/racepr/commit/d1b80f6d462769aaf12b438ac56f73796c2ac953

![image](https://github.com/kiegroup/git-backporting/assets/109468362/d9af6d71-7323-4339-878b-2c12e6d4bf44)
