### ISSUE TITLE
target-branch-pattern fails to push the branch

### ISSUE THREAD

**Issue by earl-warren** [kiegroup/git-backporting#121]
**Describe the bug**
target-branch-pattern detecting the same branch as target-branch will fail with 

**To Reproduce**

```yaml
#      - uses: https://code.forgejo.org/forgejo/git-backporting@23967a28fa7fed4c139e224e905d99b26fc42e94
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backporting:
    runs-on: docker
    container:
      image: 'docker.io/node:20-bookworm'
    steps:
      - uses: https://code.forgejo.org/forgejo/git-backporting@0558cac6c710d5f11cb8831ed4229b3afd760645
        with:
          target-branch-pattern: "^backport/(?<target>(o.*))$"
          cherry-pick-options: -x
          git-client: codeberg
          auth: ${{ secrets.BACKPORT_TOKEN }}
          pull-request: ${{ github.event.pull_request.url }}
```

```sh
 git fetch origin ; git reset --hard origin/main ; branch=b$(date +%s) ; date > adsf ; git add adsf ; git commit -m 'update one' ; sleep 1 ; date > adsf ; git add adsf ; git commit -m 'update two' ; git push origin HEAD:$branch ; pr=$(forgejo-curl.sh api_json --data '{"title":"t1","head":"'$branch'","base":"main", "labels":[143]}' https://code.forgejo.org/api/v1/repos/earl-warren/racepr/pulls | jq -r .number) && forgejo-curl.sh api_json  --data '{"Do": "merge"}' https://code.forgejo.org/api/v1/repos/earl-warren/racepr/pulls/$pr/merge 
```

```
[DEBUG] [other] Cherry picking command git cherry-pick,-m,1,--strategy=recursive,--strategy-option=theirs,-x,5da41ff757836ba011c27b86f4aa2df3c5430ea7
[INFO ] [other] Pushing bp-other-5da41ff-abba01a to origin
[ERROR] [other] Something went wrong backporting to other: Error: To https://code.forgejo.org/earl-warren/racepr.git
!	refs/heads/bp-other-5da41ff-abba01a:refs/heads/bp-other-5da41ff-abba01a	[rejected] (non-fast-forward)
Done
Pushing to https://code.forgejo.org/earl-warren/racepr.git
error: failed to push some refs to 'https://code.forgejo.org/earl-warren/racepr.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
```

Matching URLs

* https://code.forgejo.org/earl-warren/racepr/actions/runs/22#jobstep-1-17
* https://code.forgejo.org/earl-warren/racepr/src/branch/main/.forgejo/workflows/race.yml#L16

**Expected behavior**
* A successful backport to the "other" branch

**Comment by lampajr** [comment]
Hi @earl-warren, thanks for reporting this issue.

I am not completely sure about this bug, this usually happens when the generated branch (in this case `bp-other-5da41ff-abba01a`) was already existing on remote and I see it is existing https://code.forgejo.org/earl-warren/racepr/src/branch/bp-other-5da41ff-abba01a.

The `target-branch-pattern` simply extracts the target branch from the PR's label (in this case `other`) then the rest of the workflow is exactly the same.

After this quick check, if I am right, the same would happen if you use `--target-branch` as well.

If you remove https://code.forgejo.org/earl-warren/racepr/src/branch/bp-other-5da41ff-abba01a and re-run the workflow, it should work.

**Comment by earl-warren** [comment]
You are right, my bad. The backport was triggered by the label event at https://code.forgejo.org/earl-warren/racepr/actions/runs/23 and created the backport successfully. Sorry for the noise.

**Comment by lampajr** [comment]
> You are right, my bad. The backport was triggered by the label event at https://code.forgejo.org/earl-warren/racepr/actions/runs/23 and created the backport successfully. Sorry for the noise.

No worries at all, this is a good reference for anyone else will experience similar issues in the future :pray: 

PS: will close this issue as `not planned`
