### ISSUE TITLE
Add a comment to the backported PR on failure

### ISSUE THREAD

**Issue by earl-warren** [kiegroup/git-backporting#123]
**Is your feature request related to a problem? Please describe.**
A backport failing on a merged PR will show in the commit status as a failed run. But the developer does not watch the closed PR and it will likely be unnoticed. 

**Describe the solution you'd like**
A comment is added to the original PR with a message that could be as simple as "The backport to <branch> failed." The developers watching the PR will be notified even if they are not watching the builds.

**Comment by lampajr** [comment]
Thanks for opening this issue @earl-warren, I absolutely agree this would be a great feature!

> A comment is added to the original PR with a message that could be as simple as "The backport to failed."

As you suggested, as first implementation I'd go with some fixed message on the original pull request .. after that we can think if we want to make the message configurable (if there will be a need or request).

Additionally I'd make this _alert_ configurable such that users who don't want to be notified this way can simply disable it (or maybe keep this as disabled by default for backward compatibility).

**Comment by earl-warren** [comment]
Yeah! Would you be ok to tag a release? That would allow me to upgrade the Forgejo workflows :heart:

**Comment by lampajr** [comment]
> Yeah! Would you be ok to tag a release? That would allow me to upgrade the Forgejo workflows :heart: 

Yeah, I am planning to do that tomorrow morning. I'll notify you here once done, if that works for you.

**Comment by earl-warren** [comment]
Perfect.

**Comment by lampajr** [comment]
> Perfect.

Released both versions:
- https://github.com/kiegroup/git-backporting/releases/tag/v4.8.0
- https://github.com/kiegroup/git-backporting/releases/tag/v4 (still done manually)
