### ISSUE TITLE
a failed backport my taint other backports

### ISSUE THREAD

**Issue by earl-warren** [kiegroup/git-backporting#144]
**Describe the bug**

When two or more backports are scheduled in one run, one failing will fail to reset the working tree. It is then re-used by the next backport which will fail because of the lingering content.

**To Reproduce**
1. create a PR that can be cleanly backported to one branch but not another
2. backport to two branches in one go
3. See that the failed backport taints the other backport and prevents it from completing

**Expected behavior**

The failed backport does not impact the other backports

**Additional context**

* Logs: [backport-backporting-287055.log.gz](https://github.com/user-attachments/files/17537999/backport-backporting-287055.log.gz)
* Failed run: https://codeberg.org/forgejo/forgejo/actions/runs/38075
* Corresponding workflow: https://codeberg.org/forgejo/forgejo/src/branch/forgejo/.forgejo/workflows/backport.yml

**Comment by lampajr** [comment]
Hi @earl-warren, I've never faced such issue but we usually have just one stable branch at a time to backport to so maybe that's why!

I'll try to reproduce it and find a possible fix, I'll keep you posted 💪🏻

**Comment by earl-warren** [comment]
I'm actually surprised that Forgejo never ran into that problem before. There is a fair amount of backporting to the two active stable branches.

I also want to say git-backporting does a great service, daily, to the Forgejo community and proved to be very reliable.

**Comment by lampajr** [comment]
> I'm actually surprised that Forgejo never ran into that problem before. There is a fair amount of backporting to the two active stable branches.

Yeah, if you have that setup it is weird that this is the first time you experience it. Let's see if I can find something useful.. 🤞🏻 

> I also want to say git-backporting does a great service, daily, to the Forgejo community and proved to be very reliable.

I'm really glad to hear that, I hope to keep it up!!

**Comment by earl-warren** [comment]
> Yeah, if you have that setup it is weird that this is the first time you experience it. 

It only means this particular combo never happened. I think it is fine if the fail backport is the last one.

**Comment by lampajr** [comment]
Ok after a quick look, it seems the issue happens only as you already pointed out:
- Multiple backports in the same execution
- And one of the backports fails (NOT the last one)

In this scenario, the repository is not properly cleaned up/reset and therefore the next backport (the ones after the failed backport) will fail right away with:

```bash
error: you need to resolve your current index first
```

So, I think it should be enough to reset the working tree just before the backport starts

**Comment by earl-warren** [comment]
I agree: a hard reset should be enough.
