### ISSUE TITLE
Make merge strategy option configurable

### ISSUE THREAD

**Issue by mandre** [kiegroup/git-backporting#62]
The current `theirs` strategy option is not always desirable since it can result in surprising behavior as seen in https://github.com/gophercloud/gophercloud/pull/2685.

We should provide a way to configure the merge strategy, or at a minimum disable the automatic conflict resolution, so that merge conflicts result in an error.

**Comment by mandre** [comment]
Yes, absolutely. Thanks for the great support :rocket:

**Comment by lampajr** [comment]
@mandre @pierreprinetti the change is on `main` branch if you want to give it a try.
