### ISSUE TITLE
Add some comments in the backporting pull request

### ISSUE THREAD

**Issue by lampajr** [kiegroup/git-backporting#70]
Allow users to add extra information in the generated backporting pull request as comments.

**Comment by tarilabs** [comment]
for instance here:
<img width="778" alt="Screenshot 2023-07-27 at 11 30 31" src="https://github.com/kiegroup/git-backporting/assets/1699252/0e3fa20d-b1e5-482e-8856-084734103ee6">

I did not realize what to do, beyond reviewing the code as requested by the bot.

Then Tristan here shown me it was enough to trigger the CI manually: https://github.com/kiegroup/drools/pull/5408#issuecomment-1653022109

So in addition to
```
Backport: #5406
```

it would be helpful to add some further instructions such as "please manually approve/run the CI with the usual comments"

**Comment by tarilabs** [comment]
_ as part of the pr description_ would work perfectly for me, please

**Comment by tarilabs** [comment]
ie: just before/after the "Backport: #5406" and _not_ in the `<details/>`
