### ISSUE TITLE
Retrieve target branch from PR label(s)

### ISSUE THREAD

**Issue by lampajr** [kiegroup/git-backporting#75]
There are use cases where the target branch is not always fixed, instead it is dynamically computed from the original PR label(s).
That is why we created this additional workflow step [1] to properly parse labels with a prefixed pattern and extracting the target branch from them, this could be hard to maintain and error-prone.

**Proposal**: integrate this step in the tool itself, in this way `target-branch` will become optional and you can provide the regex/pattern to use in order to extract the target branch from the original PR labels, if any.

[1] https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/.github/workflows/pr-backporting.yml#L12-L25
```[tasklist]
### Tasks
- [ ] https://github.com/kiegroup/git-backporting/issues/77
```

**Comment by earl-warren** [comment]
here is a [snippet](https://github.com/tibdex/backport/blob/main/src/backport.ts#L35-L52) for inspiration, from a similar action:

```js

const getBaseBranches = ({
  labelRegExp,
  payload,
}: Readonly<{
  labelRegExp: RegExp;
  payload: PullRequestClosedEvent | PullRequestLabeledEvent;
}>): string[] => {
  if ("label" in payload) {
    const base = getBaseBranchFromLabel(payload.label.name, labelRegExp);
    return base ? [base] : [];
  }

  return compact(
    payload.pull_request.labels.map((label) =>
      getBaseBranchFromLabel(label.name, labelRegExp),
    ),
  );
};
```

**Comment by lampajr** [comment]
That's a good hint, thanks @earl-warren for the reference!
