### ISSUE TITLE
GITLAB_TOKEN environment variable not used for API call

### ISSUE THREAD

**Issue by peat-psuwit** [kiegroup/git-backporting#96]
Step to reproduce:
1. Set `GITLAB_TOKEN` environment variable.
2. Call `git-backporting` without `--auth`. Pulling and pushing Git branches will succeed, but the attempt to create a merge request will fail.

It seems like the environment variable is parsed in `PullRequestConfigsParser.parseAndValidate()`. However, this seems to happen before the `GitClient` is created, so it's not used inside it.

<details>
<summary>Log</summary>
<pre>
[DEBUG] Setting up gitlab client: apiUrl=https://gitlab.com/api/v4, token=****
[DEBUG] Parsing configs..
[INFO ] Auth argument not provided, checking available tokens from env..
[DEBUG] [ubports/focal] Cloning repo..
[INFO ] [ubports/focal] Cloning repository https://gitlab.com/peat-psuwit/ut-declarative-camera.git to /builds/peat-psuwit/gitlab-auto-backporter/gitlab-auto-backporter-cOoDLk/bp
[DEBUG] [ubports/focal] Creating local branch..
[INFO ] [ubports/focal] Creating branch backports/mr-1/ubports/focal
[DEBUG] [ubports/focal] Cherry picking commits..
[INFO ] [ubports/focal] Cherry picking e6ba6be7b155b5aa86b0b2968f91cda9471ff50d
[INFO ] [ubports/focal] Pushing backports/mr-1/ubports/focal to origin
[INFO ] [ubports/focal] Creating pull request backports/mr-1/ubports/focal -> ubports/focal
[INFO ] [ubports/focal] {
  "owner": "peat-psuwit",
  "repo": "ut-declarative-camera",
  "head": "backports/mr-1/ubports/focal",
  "base": "ubports/focal",
  "title": "[ubports/focal] Personal/peat psuwit/test",
  "body": "**Backport:** https://gitlab.com/peat-psuwit/ut-declarative-camera/-/merge_requests/1\r\n\r\nTest\n\nX-UBports-Depends: !1 \nX-UBports-Depends: ubports/development/core/morph-browser!574 \nX-UBports-Depends: https://gitlab.com/ubports/development/core/morph-browser/-/merge_requests/574",
  "reviewers": [
    "peat-psuwit"
  ],
  "assignees": [],
  "labels": [],
  "comments": []
}
[ERROR] [ubports/focal] Something went wrong backporting to ubports/focal: AxiosError: Request failed with status code 401
[ERROR] [ubports/focal] Error: Failure occurred during one of the backports: [AxiosError: Request failed with status code 401]
[INFO ] [ubports/focal] Process failed
</details>

**Comment by lampajr** [comment]
Good spot @peat-psuwit !
Yeah right now the environment variables are fetched during the `PullRequestConfigsParser.parseAndValidate()` but this happens _after_ the `GitClient` is initialized, therefore every request that is made using the `GitClient` does not have the proper token setup.

Note that this bug is affecting all platforms, not just `GITLAB`.
