### ISSUE TITLE
When cherry-pick conflict cannot be resolved

### ISSUE THREAD

**Issue by Yaminyam** [kiegroup/git-backporting#97]
It seems that there are cases where the conflict cannot be resolved with git cherry-pick -m 1 --strategy=recursive --strategy-option=theirs.
What I have experienced is that in the case of a commit that modifies a file that does not yet exist in the branch to be backported, a conflict occurs even with the theirs option.
How do you behave or handle these cases?

**Comment by lampajr** [comment]
Hi @Yaminyam, thanks for raising this question!

The limitation of this tool actually matches the limitation of the `cherry-pick` git command when talking about _conflicts resolution_, I tried to make the toolt as configurable and flexible [1] as possible such that you can set the _merge strategy_ that fits better your use case (from those listed in the git documentation [2]).

Given that, if you are in a situation where an _automated conflict resolution_ cannot be applied the only way I can see it is to consider that as an _outlier_, i.e., in such cases we were used to manually create the cherry-picked pull/merge request.

So my suggestion is to use the _default merge strategy_ that works better for most of your use cases and change it for those cases where that was not good enough (or use the manual/raw approach to cherry-pick that commit(s)).

I hope I have fully answered your question, if not feel free to add more details :rocket: 


[1] https://github.com/kiegroup/git-backporting?tab=readme-ov-file#default-cherry-pick-strategy
[2] https://git-scm.com/docs/git-cherry-pick#Documentation/git-cherry-pick.txt---strategyltstrategygt

**Comment by Yaminyam** [comment]
Thank you for your kind reply.
I am also implementing backport automation, and I asked this question because I thought you would be familiar with it because I have experienced related problems.
If cherry-pick fails, I'm thinking of handling it manually by leaving a comment in the original pr.
